name: Run tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Install dependencies with Node.js lts
        uses: actions/setup-node
        with:
          node-version: lts
          cache: npm
      - run: npm ci
      - name: Run tests
        id: test
        run: npm test
